name: "Build And Run Tests"

on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - "cmd/**"
      - "internal/**"
      - "pkg/**"
      - "tests/**"
  workflow_dispatch:

jobs:
  build-and-test-backend:
    name: Build And Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        run: |
          go mod tidy  # Ensures all dependencies are in place
      - name: Run Unit Tests
        run: |
          cd pkg && go test -v ./...  # Run all tests in the project with verbose output
      - name: Run Integration Tests
        run: |
          cd tests/integration_tests && go test -v ./...  # Run all tests in the project with verbose output
